In [57]:
import numpy as np

Array creation

In [58]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [59]:
arr = np.array((1,2,3),dtype=np.float64)
arr

array([1., 2., 3.])

In [60]:
lst = [3,4,5,6,2,1]
arr = np.array(lst)
arr

array([3, 4, 5, 6, 2, 1])

In [61]:
arr.reshape(2,3)

array([[3, 4, 5],
       [6, 2, 1]])

np.zeroes(shape)

In [62]:
arr = np.zeros((2,2),dtype = np.int64)
arr

array([[0, 0],
       [0, 0]])

np.ones(shape)

In [63]:
arr= np.ones((3,2),dtype = np.int64)
arr

array([[1, 1],
       [1, 1],
       [1, 1]])

np.empty(shape)

In [64]:
arr = np.empty((2, 2))
arr.dtype

dtype('float64')

np.full(shape, fill_value)  used to fill with one scalar value

In [65]:
arr = np.full((2,2),5)
arr

array([[5, 5],
       [5, 5]])

np.tile(array,reps)

In [66]:
arr = np.tile([1,2,3],(2,2))
arr

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [67]:
arr = np.tile([1,2,3],(2,1))
arr

array([[1, 2, 3],
       [1, 2, 3]])

np.eye(n, m) or np.identity(n)

In [68]:
arr = np.eye(3,3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
arr = np.eye(2)
arr

array([[1., 0.],
       [0., 1.]])

In [70]:
arr = np.identity(2)
arr

array([[1., 0.],
       [0., 1.]])

np.arange(start, stop, step)  similar to range of python, end point excluded

In [71]:
arr = np.arange(2,10,2)
arr

array([2, 4, 6, 8])

In [72]:
arr = np.arange(30,40,dtype = np.float64)
arr

array([30., 31., 32., 33., 34., 35., 36., 37., 38., 39.])

In [73]:
arr[2] = 10
arr.reshape(5,2).astype('float64')

array([[30., 31.],
       [10., 33.],
       [34., 35.],
       [36., 37.],
       [38., 39.]])

In [74]:
arr = np.arange(20,30).reshape(5,2).astype('float64')
arr

array([[20., 21.],
       [22., 23.],
       [24., 25.],
       [26., 27.],
       [28., 29.]])

np.linspace(start, stop, num) end point included

In [75]:
arr = np.linspace(2,10)
arr

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [76]:
arr = np.linspace(2,10, num =5)
arr

array([ 2.,  4.,  6.,  8., 10.])

In [77]:
arr = np.linspace(2,10,5,dtype = 'str')
arr

array(['2.0', '4.0', '6.0', '8.0', '10.0'], dtype='<U32')

In [78]:
r_num = np.random.uniform(101,201,10)
print("random.uniform\n", r_num) 

random.uniform
 [200.79632866 195.96081114 185.5968648  106.60180506 115.139491
 120.88052773 177.63895176 192.93911865 110.35954557 165.19901222]


In [79]:
np.random.normal(0, 1, 5)


array([-1.25007315, -0.16572108,  0.597286  , -0.77293769,  0.58942624])

Deep Copy - Shallow Copy

In [80]:
marks = np.array([33,44,77,85,45,32,47,88,90])
marks

array([33, 44, 77, 85, 45, 32, 47, 88, 90])

In [81]:
top_marks = marks[:5]          #Shallow copy
top_marks[0]=11       #original marks is also changed
marks

array([11, 44, 77, 85, 45, 32, 47, 88, 90])

In [82]:
top_marks[:] = 99
print(marks)
print(top_marks)

[99 99 99 99 99 32 47 88 90]
[99 99 99 99 99]


In [83]:
marks = np.array([33,44,77,85,45,32,47,88,90])
marks_copy = marks.copy()     #Deep copy
marks_copy[:] = 99
print(marks_copy)
print(marks)          #no Changes in original

[99 99 99 99 99 99 99 99 99]
[33 44 77 85 45 32 47 88 90]


Conditional selection of filtering

In [84]:
marks = np.array([69,26,78,91.54,34])

In [85]:
passed = marks > 35
passed

array([ True, False,  True,  True, False])

In [86]:
marks[passed].astype(int)

array([69, 78, 91])

In [87]:
marks[marks < 35].astype(int)        #failed students

array([26, 34])

In [88]:
arr = np.arange(0,10).reshape(-1,2)    #numpy can guess the second dimension if one dimension is given
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [89]:
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min()) 
print(arr.var())
print(arr.std())

45
4.5
9
0
8.25
2.8722813232690143


In [90]:
np.ptp(arr)   #(range max-min)

np.int64(9)

In [91]:
np.median(arr)

np.float64(4.5)

In [92]:
arr.argmax()

np.int64(9)

In [93]:
arr.argmin()

np.int64(0)

In [94]:
arr.argsort()

array([[0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1]])

In [95]:
print(arr.ndim)

2


arr.clip(min,max)  limit values to a range

In [96]:
arr.clip(3,7)

array([[3, 3],
       [3, 3],
       [4, 5],
       [6, 7],
       [7, 7]])

In [97]:
arr = [4,5,1,2,0,7,3,8]
print(arr)
arr.sort(reverse= True)
arr

[4, 5, 1, 2, 0, 7, 3, 8]


[8, 7, 5, 4, 3, 2, 1, 0]

In [98]:
np.sort(arr)[::-1]

array([8, 7, 5, 4, 3, 2, 1, 0])

In [99]:
arr = np.array(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(type(arr))

1
(8,)
8
<class 'numpy.ndarray'>


2D array 

In [100]:
darray = np.arange(20,40,2).reshape(2,5)
darray

array([[20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [101]:
darray.ndim

2

In [102]:
darray[1][3]

np.int64(36)

In [103]:
darray[1:,1:]

array([[32, 34, 36, 38]])

In [104]:
darray[:,0]

array([20, 30])

In [105]:
darray[[0,1,]]   #fancy indexing

array([[20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

Reshaping/Manipulation

In [106]:
darray.flatten()   #safe

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [107]:
darray.ravel()   # fast

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [108]:
np.resize(darray,(4,4))     #does not change original, replaces by repeating data, if size is large

array([[20, 22, 24, 26],
       [28, 30, 32, 34],
       [36, 38, 20, 22],
       [24, 26, 28, 30]])

In [109]:
darray = darray.copy()
darray.resize(4,4)             #changes original array by replacing 0s if size is large
darray

array([[20, 22, 24, 26],
       [28, 30, 32, 34],
       [36, 38,  0,  0],
       [ 0,  0,  0,  0]])

In [112]:
darray[:,-1]

array([26, 34,  0,  0])

In [113]:
darray[-1,:]

array([0, 0, 0, 0])

In [114]:
darray[-1,:-1]

array([0, 0, 0])

In [117]:
arr1 = np.ones((5,5),dtype = int)
arr1[1:-1,1:-1] = 0
arr1

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [122]:
arr1d = np.arange(1,4).reshape(1,3)
arr2d = np.arange(11,20).reshape(3,3)
arr1d+arr2d

array([[12, 14, 16],
       [15, 17, 19],
       [18, 20, 22]])

vstack, hstack

In [133]:
a = np.array([[1,2,3]])
b = np.array([[4,5,6]])

In [134]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [135]:
np.hstack((a,b))

array([[1, 2, 3, 4, 5, 6]])

In [138]:
np.concatenate((a,b),axis=0)    #similar to vstack

array([[1, 2, 3],
       [4, 5, 6]])

In [139]:
np.concatenate((a,b),axis=1)     #simialr to hstack

array([[1, 2, 3, 4, 5, 6]])

In [140]:
np.transpose(a)

array([[1],
       [2],
       [3]])

np.split(array, indices_or_sections, axis=0)    --- even splits or equal size divison

In [150]:
arr = np.array([1,2,3,4,5,6])     
result = np.split(arr, 2)
result

[array([1, 2, 3]), array([4, 5, 6])]

In [143]:
result = np.split(arr, [3,5])
result

[array([1, 2, 3]), array([4, 5]), array([6])]

In [144]:
arr2d = np.array([[1,2],
                [3,4],
                [5,6],
                [7,8]])

np.split(arr2d, 2, axis=0)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

In [145]:
np.split(arr2d, 2, axis=1)

[array([[1],
        [3],
        [5],
        [7]]),
 array([[2],
        [4],
        [6],
        [8]])]

In [154]:
np.array_split(arr,4)           #Allows unequal splits         

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [155]:
arr_2d = np.array([[1, 12, 3, 4],
                   [15, 11, 7, 8],
                   [1, 12, 3, 4],
                   [13, 14, 15, 16]])

In [157]:
np.unique(arr_2d)

array([ 1,  3,  4,  7,  8, 11, 12, 13, 14, 15, 16])

In [156]:
np.unique(arr_2d,axis=0)        #unique rows

array([[ 1, 12,  3,  4],
       [13, 14, 15, 16],
       [15, 11,  7,  8]])

np.where(condition, x, y)

In [158]:
arr = np.array([10, 5, 8, 20])
result = np.where(arr > 10, 1, 0)
result

array([0, 0, 0, 1])

In [163]:
np.where(arr > 10)

(array([3]),)

In [164]:
arr[np.where(arr > 10)]

array([20])

Bool array

In [167]:
arr = np.ones((2,2),dtype = bool)
arr[1,0] = 0
arr

array([[ True,  True],
       [False,  True]])